CREATE TABLE announcements (
                               id bigint NOT NULL,
                               body text,
                               created_at timestamp(6),
                               title varchar(255),
                               author_id bigint,
                               course_id bigint
);

ALTER TABLE announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE assignments (
                             id bigint NOT NULL,
                             created_at timestamp(6),
                             description text,
                             due_date timestamp(6),
                             max_score integer,
                             title varchar(255),
                             course_id bigint
);

ALTER TABLE assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE courses (
                         id bigint NOT NULL,
                         code varchar(255) NOT NULL,
                         created_at timestamp(6) NOT NULL,
                         description text,
                         name varchar(255) NOT NULL,
                         instructor_id bigint NOT NULL,
                         location varchar(255),
                         schedule varchar(255)
);

ALTER TABLE courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE enrolments (
                            id bigint NOT NULL,
                            enrolled_at timestamp(6) NOT NULL,
                            course_id bigint NOT NULL,
                            student_id bigint NOT NULL
);

ALTER TABLE enrolments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE materials (
                           id bigint NOT NULL,
                           filename varchar(255),
                           section varchar(255),
                           size bigint,
                           uploaded_at timestamp(6),
                           url varchar(255),
                           course_id bigint
);

ALTER TABLE materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE posts (
                       id bigint NOT NULL,
                       body text,
                       created_at timestamp(6),
                       title varchar(255),
                       author_id bigint,
                       course_id bigint
);

ALTER TABLE posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE replies (
                         id bigint NOT NULL,
                         body text,
                         created_at timestamp(6),
                         author_id bigint,
                         post_id bigint
);

ALTER TABLE replies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE submissions (
                             id bigint NOT NULL,
                             feedback text,
                             filename varchar(255),
                             score integer,
                             status varchar(255),
                             submitted_at timestamp(6),
                             assignment_id bigint,
                             student_id bigint,
                             CONSTRAINT submissions_status_check CHECK (status IN ('SUBMITTED','GRADED','LATE'))
);

ALTER TABLE submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE users (
                       id bigint NOT NULL,
                       name varchar(255) NOT NULL,
                       email varchar(255) NOT NULL,
                       password varchar(255) NOT NULL,
                       role varchar(255) NOT NULL,
                       created_at timestamp NOT NULL
);

CREATE SEQUENCE users_id_seq;

ALTER SEQUENCE users_id_seq OWNED BY users.id;

ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');

-- PRIMARY KEYS

ALTER TABLE announcements ADD PRIMARY KEY (id);
ALTER TABLE assignments ADD PRIMARY KEY (id);
ALTER TABLE courses ADD PRIMARY KEY (id);
ALTER TABLE enrolments ADD PRIMARY KEY (id);
ALTER TABLE materials ADD PRIMARY KEY (id);
ALTER TABLE posts ADD PRIMARY KEY (id);
ALTER TABLE replies ADD PRIMARY KEY (id);
ALTER TABLE submissions ADD PRIMARY KEY (id);
ALTER TABLE users ADD PRIMARY KEY (id);

-- UNIQUE

ALTER TABLE courses ADD CONSTRAINT uk_courses_code UNIQUE (code);
ALTER TABLE enrolments ADD CONSTRAINT uk_enrolment UNIQUE (student_id, course_id);
ALTER TABLE users ADD CONSTRAINT uk_user_email UNIQUE (email);

-- FOREIGN KEYS

ALTER TABLE announcements ADD CONSTRAINT fk_ann_author FOREIGN KEY (author_id) REFERENCES users(id);
ALTER TABLE announcements ADD CONSTRAINT fk_ann_course FOREIGN KEY (course_id) REFERENCES courses(id);

ALTER TABLE assignments ADD CONSTRAINT fk_assignment_course FOREIGN KEY (course_id) REFERENCES courses(id);

ALTER TABLE courses ADD CONSTRAINT fk_course_instructor FOREIGN KEY (instructor_id) REFERENCES users(id);

ALTER TABLE enrolments ADD CONSTRAINT fk_enrol_course FOREIGN KEY (course_id) REFERENCES courses(id);
ALTER TABLE enrolments ADD CONSTRAINT fk_enrol_student FOREIGN KEY (student_id) REFERENCES users(id);

ALTER TABLE materials ADD CONSTRAINT fk_material_course FOREIGN KEY (course_id) REFERENCES courses(id);

ALTER TABLE posts ADD CONSTRAINT fk_post_author FOREIGN KEY (author_id) REFERENCES users(id);
ALTER TABLE posts ADD CONSTRAINT fk_post_course FOREIGN KEY (course_id) REFERENCES courses(id);

ALTER TABLE replies ADD CONSTRAINT fk_reply_author FOREIGN KEY (author_id) REFERENCES users(id);
ALTER TABLE replies ADD CONSTRAINT fk_reply_post FOREIGN KEY (post_id) REFERENCES posts(id);

ALTER TABLE submissions ADD CONSTRAINT fk_submission_student FOREIGN KEY (student_id) REFERENCES users(id);
ALTER TABLE submissions ADD CONSTRAINT fk_submission_assignment FOREIGN KEY (assignment_id) REFERENCES assignments(id);