server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/backend_db?currentSchema=public
    username: mac
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}

jwt:
  secret: ${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS1mb3Itand0LXRva2VuLW15LXN1cGVyLXNlY3JldC1rZXk=}
  expiration: ${JWT_EXPIRATION:86400000}