server:
  port: ${PORT:8080}

spring:
  application:
    name: backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/backend_db}
    username: ${DB_USERNAME:backend_user}
    password: ${DB_PASSWORD:Backend123!}

#  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/backend_db_flyway_v2}
#    username: ${DB_USERNAME:mac}
#    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
  upload:
    dir: ${UPLOAD_DIR:uploads}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}